name: calendar_date_picker2
description: A lightweight and customizable calendar picker based on Flutter CalendarDatePicker, with support for single date picker, range picker and multi picker.
version: 1.1.5
homepage: https://github.com/theideasaler/calendar_date_picker2

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

screenshots:
  - description: CalendarDatePicker2 day view demo
    path: example/screenshots/custom_range_picker_demo.png
  - description: CalendarDatePicker2 month view demo
    path: example/screenshots/calendar_date_picker_month_view.png
  - description: CalendarDatePicker2 year view demo
    path: example/screenshots/custom_range_picker_demo_2.png
  - description: CalendarDatePicker2 scroll view demo
    path: example/screenshots/custom_range_picker_demo_scroll.png